### ISSUE TITLE
[Tutorial] Add a new monster

### ISSUE THREAD

**Issue by DevaGwava** [xandao-dev/flyff-bots#1]
how to add new monster

**Comment by xandao-dev** [comment]
Hello, you're probably talking about the Foreground Vision Bot, right?

1. Navigate to "foreground_vision_bot/assets/names"
2. Now you need to add an image with the name of the new monster, I recommend you to take a look at the images inside this folder to see how to make the screenshot, it needs to be accurate.
3. Go back to "foreground_vision_bot/assets" and you will see a file called Assets.py, I suggest you to read the file and add your new monster there, following the other monsters already added.

**Comment by aiDoMiNate** [comment]
I tried it But it couldn't find the monster. 
Can it be used on  Server Flyff universe on Web browser ?

**Comment by aiDoMiNate** [comment]
> Hello, you're probably talking about the Foreground Vision Bot, right?
> 
> 1. Navigate to "foreground_vision_bot/assets/names"
> 2. Now you need to add an image with the name of the new monster, I recommend you to take a look at the images inside this folder to see how to make the screenshot, it needs to be accurate.
> 3. Go back to "foreground_vision_bot/assets" and you will see a file called Assets.py, I suggest you to read the file and add your new monster there, following the other monsters already added.

I tried it But it couldn't find the monster.
Can it be used on Server Flyff universe on Web browser ?

**Comment by xandao6** [comment]
Wow, I didn't know this exists. Probably doesn't work without some adjusts.

**Comment by aiDoMiNate** [comment]
> Wow, I didn't know this exists. Probably doesn't work without some adjusts.

Can you go in and test it out?
