### ISSUE TITLE
Can you make it attack monster via specific key?

### ISSUE THREAD

**Issue by ghost** [xandao-dev/flyff-bots#26]

**Comment by xandao-dev** [comment]
I forgot to add in the documentation, but the bot uses F1 to trigger the attack, so you should put the attack action in this key. 
In case you want to use another key other than F1?

**Comment by ghost** [comment]
Hey can you help me set it up? can we go team viewer?

**Comment by xandao-dev** [comment]
Sure, reach me at whatsapp or linkedin.
https://github.com/xandao-dev
