### ISSUE TITLE
Failed - virus detected when trying to download you git.

### ISSUE THREAD

**Issue by ghost** [xandao-dev/flyff-bots#28]

**Comment by xandao-dev** [comment]
Hi, it's because of these tools: https://github.com/xandao-dev/flyff-bots/tree/main/other/gui-inspect-tool

Tools I used to inspect the game while I was building the bot, but the bot doesn't need them to run. So I'm going to move them to a zip and it won't bother anyone again.

**Comment by xandao-dev** [comment]
@direrFlood Done, could you check it again?
